/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControllerAction: typeof import('./components/controller/ControllerAction.vue')['default']
    ControllerFunction: typeof import('./components/controller/ControllerFunction.vue')['default']
    ControllerJoystick: typeof import('./components/controller/ControllerJoystick.vue')['default']
    GameAccount: typeof import('./components/GameAccount.vue')['default']
    GameBgm: typeof import('./components/GameBgm.vue')['default']
    GameCloud: typeof import('./components/GameCloud.vue')['default']
    GameControls: typeof import('./components/GameControls.vue')['default']
    GameHelp: typeof import('./components/GameHelp.vue')['default']
    GameMenu: typeof import('./components/GameMenu.vue')['default']
    GamePad: typeof import('./components/GamePad.vue')['default']
    GameToast: typeof import('./components/GameToast.vue')['default']
    GithubLink: typeof import('./components/controller/GithubLink.vue')['default']
    IMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    IMdiAccountCircleOutline: typeof import('~icons/mdi/account-circle-outline')['default']
    IMdiCloudOutline: typeof import('~icons/mdi/cloud-outline')['default']
    IMdiCloudUpload: typeof import('~icons/mdi/cloud-upload')['default']
    IMdiContentSave: typeof import('~icons/mdi/content-save')['default']
    IMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    IMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHelp: typeof import('~icons/mdi/help')['default']
    IMdiHistory: typeof import('~icons/mdi/history')['default']
    IMdiRestart: typeof import('~icons/mdi/restart')['default']
    IMdiTrayArrowDown: typeof import('~icons/mdi/tray-arrow-down')['default']
    IMdiVolumeHigh: typeof import('~icons/mdi/volume-high')['default']
    IMdiVolumeOff: typeof import('~icons/mdi/volume-off')['default']
  }
}
